### ISSUE TITLE
Error: obsolete definition (S_PARTY_MEMBER_LIST.8)

### ISSUE THREAD

**Issue by FrankMora** [Risenio/fps-utils#9]
```
[04:55:29.555] Error: [dispatch] [fps-utils] hook: Error: obsolete definition (S_PARTY_MEMBER_LIST.8)
    at Dispatch.createHook (G:\Games\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch.js:230:27)
    at Dispatch.hook (G:\Games\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch.js:265:27)
    at Proxy.hook (G:\Games\TeraToolbox\bin\mod.js:280:36)
    at new FpsUtils (G:\Games\TeraToolbox\mods\fps-utils-master\lib\index.js:1146:6)
    at new <anonymous> (G:\Games\TeraToolbox\bin\mod-legacy-wrapper.js:144:13)
    at Mod.loadNetworkInstance (G:\Games\TeraToolbox\bin\mod.js:595:31)
    at ModManager.loadNetwork (G:\Games\TeraToolbox\bin\mod-manager.js:252:20)
    at G:\Games\TeraToolbox\bin\mod-manager.js:233:22
    at Map.forEach (<anonymous>)
    at ModManager.loadAllNetwork (G:\Games\TeraToolbox\bin\mod-manager.js:231:25)
```

**Comment by Risenio** [comment]
Fixed in [46b3233](https://github.com/Risenio/fps-utils/commit/46b323326c8923e5f18c120d612fed1c05a07c24).
thanks for reporting!
